// <auto-generated />
using System;
using DataAccessEFLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccessEFLayer.Migrations
{
    [DbContext(typeof(LibraryDbContext))]
    partial class LibraryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataAccessEFLayer.Entities.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Без имени");

                    b.HasKey("Id");

                    b.ToTable("Authors", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfBirth = new DateOnly(2001, 11, 20),
                            Name = "chel chelikov"
                        },
                        new
                        {
                            Id = 2,
                            DateOfBirth = new DateOnly(2002, 10, 21),
                            Name = "chuvak chuvakov"
                        },
                        new
                        {
                            Id = 3,
                            DateOfBirth = new DateOnly(2003, 9, 22),
                            Name = "patsan patsanov"
                        },
                        new
                        {
                            Id = 4,
                            DateOfBirth = new DateOnly(2004, 8, 23),
                            Name = "marat kaskinov"
                        });
                });

            modelBuilder.Entity("DataAccessEFLayer.Entities.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AuthorId")
                        .HasColumnType("int");

                    b.Property<int>("PublishedYear")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Без названия");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Books", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            PublishedYear = 0,
                            Title = "shi1"
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 2,
                            PublishedYear = 0,
                            Title = "shi2"
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 3,
                            PublishedYear = 0,
                            Title = "shi3"
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 2,
                            PublishedYear = 0,
                            Title = "shi4"
                        });
                });

            modelBuilder.Entity("DataAccessEFLayer.Entities.Book", b =>
                {
                    b.HasOne("DataAccessEFLayer.Entities.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Author");
                });

            modelBuilder.Entity("DataAccessEFLayer.Entities.Author", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
